
package jogodavelha;

public class JFrame extends javax.swing.JFrame {

   static char [][] tabuleiro = new char [3][3];

   boolean jogada = false;
   
   int pX, pO;
   int contador;
    
    public JFrame() {
        initComponents();
        limpaTabuleiro();
        contador=0;
        pX=0;
        pO=0;
        this.jX.setText("X:"+pX);
        this.jO.setText("O:"+pO);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        jTitle = new javax.swing.JLabel();
        jWin = new javax.swing.JLabel();
        j1 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jX = new javax.swing.JLabel();
        jO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));

        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        j8.setBackground(new java.awt.Color(51, 51, 51));
        j8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        j8.setForeground(new java.awt.Color(255, 255, 255));
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });

        j9.setBackground(new java.awt.Color(51, 51, 51));
        j9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        j9.setForeground(new java.awt.Color(255, 255, 255));
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });

        jTitle.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        jTitle.setForeground(new java.awt.Color(0, 153, 153));
        jTitle.setText("Jogo da Velha #");

        jWin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jWin.setForeground(new java.awt.Color(255, 255, 255));

        j1.setBackground(new java.awt.Color(51, 51, 51));
        j1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        j1.setForeground(new java.awt.Color(255, 255, 255));
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setBackground(new java.awt.Color(51, 51, 51));
        j2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        j2.setForeground(new java.awt.Color(255, 255, 255));
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        j3.setBackground(new java.awt.Color(51, 51, 51));
        j3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        j3.setForeground(new java.awt.Color(255, 255, 255));
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        j4.setBackground(new java.awt.Color(51, 51, 51));
        j4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        j4.setForeground(new java.awt.Color(255, 255, 255));
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        j5.setBackground(new java.awt.Color(51, 51, 51));
        j5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        j5.setForeground(new java.awt.Color(255, 255, 255));
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        j6.setBackground(new java.awt.Color(51, 51, 51));
        j6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        j6.setForeground(new java.awt.Color(255, 255, 255));
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        j7.setBackground(new java.awt.Color(51, 51, 51));
        j7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        j7.setForeground(new java.awt.Color(255, 255, 255));
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jX.setForeground(new java.awt.Color(255, 255, 255));

        jO.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pontuação");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jWin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jX)
                    .addComponent(jO)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jWin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        j1.getAccessibleContext().setAccessibleName("j1");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    static void limpaTabuleiro(){
        int count = 1;
        for(int i=0; i<tabuleiro.length; i++){
            for(int j=0; j<tabuleiro[i].length; j++){
                tabuleiro[i][j] = Character.forDigit(count++,10);
            }

        }
        
    }
    
    void verificaGanhador(){
           
         if(velha('X')=='X'){
        this.jWin.setText("X venceu");
        this.j1.setEnabled(false);
        this.j2.setEnabled(false);
        this.j3.setEnabled(false);
        this.j4.setEnabled(false);
        this.j5.setEnabled(false);
        this.j6.setEnabled(false);
        this.j7.setEnabled(false);
        this.j8.setEnabled(false);
        this.j9.setEnabled(false);
        pX++;
        this.jX.setText("X:"+pX);
        } else if (velha('O')=='O'){
        this.jWin.setText("O venceu");
        this.j1.setEnabled(false);
        this.j2.setEnabled(false);
        this.j3.setEnabled(false);
        this.j4.setEnabled(false);
        this.j5.setEnabled(false);
        this.j6.setEnabled(false);
        this.j7.setEnabled(false);
        this.j8.setEnabled(false);
        this.j9.setEnabled(false);
        pO++;
        this.jO.setText("O:"+pO);
        }
         contador++; 
        if(contador==9 && velha('X')=='#' && velha('O')=='#'){
        this.jWin.setText("Deu velha!");
        }
        
    
    }
    
    static void marcaTabuleiro(int posicao, char marca){
        switch(posicao){
            case '1' : tabuleiro[0][0] = marca;
            break;
            case '2' : tabuleiro[0][1] = marca;
            break;
            case '3' : tabuleiro[0][2] = marca;
            break;
            case '4' : tabuleiro[1][0] = marca;
            break;
            case '5' : tabuleiro[1][1] = marca;
            break;
            case '6' : tabuleiro[1][2] = marca;
            break;
            case '7' : tabuleiro[2][0] = marca;
            break;
            case '8' : tabuleiro[2][1] = marca;
            break;
            case '9' : tabuleiro[2][2] = marca;
            break;
        }
    }
    
    static char velha(char marca){
   
        for(int i=0; i<tabuleiro.length; i++){
           for(int j=0; j<tabuleiro[i].length; j++){
         if(tabuleiro[i][0]==marca && tabuleiro[i][1]==marca&& tabuleiro[i][2]==marca){
             return marca;
         }
         if(tabuleiro[0][j]==marca && tabuleiro[1][j]==marca&& tabuleiro[2][j]==marca){
             return marca;
         }
         }
        }
        
        if(tabuleiro[0][0]==marca && tabuleiro[1][1]==marca&& tabuleiro[2][2]==marca){
             return marca;
        }
         if(tabuleiro[2][0]==marca && tabuleiro[1][1]==marca&& tabuleiro[0][2]==marca){
             return marca;
        }
        
        
         return '#';
    }
    
    
    
    
    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
      
        if(jogada==false){
        this.j1.setText("X");
        marcaTabuleiro('1', 'X');
        jogada=true;
        }else{
        this.j1.setText("O");
        marcaTabuleiro('1', 'O');
        jogada=false; 
        }
       verificaGanhador();
       this.j1.setEnabled(false);    
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
      if(jogada==false){
        this.j2.setText("X");
        marcaTabuleiro('2', 'X');
        jogada=true;
        }else{
        this.j2.setText("O");
        marcaTabuleiro('2', 'O');
        jogada=false; 
        }
       verificaGanhador();
       this.j2.setEnabled(false);    

    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
          if(jogada==false){
        this.j3.setText("X");
        marcaTabuleiro('3', 'X');
        jogada=true;
        }else{
        this.j3.setText("O");
        marcaTabuleiro('3', 'O');
        jogada=false; 
        }
      verificaGanhador(); 
      this.j3.setEnabled(false);    
    }//GEN-LAST:event_j3ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
        if(jogada==false){
        this.j4.setText("X");
        marcaTabuleiro('4', 'X');
        jogada=true;
        }else{
        this.j4.setText("O");
        marcaTabuleiro('4', 'O');
        jogada=false; 
        }
       verificaGanhador();
       this.j4.setEnabled(false);    

    }//GEN-LAST:event_j4ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
          if(jogada==false){
        this.j5.setText("X");
        marcaTabuleiro('5', 'X');
        jogada=true;
        }else{
        this.j5.setText("O");
        marcaTabuleiro('5', 'O');
        jogada=false; 
        }
        verificaGanhador();
        this.j5.setEnabled(false);    

    }//GEN-LAST:event_j5ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
          if(jogada==false){
        this.j6.setText("X");
        marcaTabuleiro('6', 'X');
        jogada=true;
        }else{
        this.j6.setText("O");
        marcaTabuleiro('6', 'O');
        jogada=false; 
        }
        verificaGanhador(); 
        this.j6.setEnabled(false);    

    }//GEN-LAST:event_j6ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        // TODO add your handling code here:
          if(jogada==false){
        this.j7.setText("X");
        marcaTabuleiro('7', 'X');
        jogada=true;
        }else{
        this.j7.setText("O");
        marcaTabuleiro('7', 'O');
        jogada=false; 
        }
       verificaGanhador(); 
       this.j7.setEnabled(false);    

    }//GEN-LAST:event_j7ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        // TODO add your handling code here:
          if(jogada==false){
        this.j8.setText("X");
        marcaTabuleiro('8', 'X');
        jogada=true;
        }else{
        this.j8.setText("O");
        marcaTabuleiro('8', 'O');
        jogada=false; 
        }
        verificaGanhador();
       this.j8.setEnabled(false);    
    }//GEN-LAST:event_j8ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
          if(jogada==false){
        this.j9.setText("X");
        marcaTabuleiro('9', 'X');
        jogada=true;
        }else{
        this.j9.setText("O");
        marcaTabuleiro('9', 'O');
        jogada=false; 
        }
        verificaGanhador(); 
        this.j9.setEnabled(false);    

    }//GEN-LAST:event_j9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        contador=0;
        jogada=false;
        limpaTabuleiro();
        this.j1.setEnabled(true);
        this.j2.setEnabled(true);
        this.j3.setEnabled(true);
        this.j4.setEnabled(true);
        this.j5.setEnabled(true);
        this.j6.setEnabled(true);
        this.j7.setEnabled(true);
        this.j8.setEnabled(true);
        this.j9.setEnabled(true);
        
        this.j1.setText("");
        this.j2.setText("");
        this.j3.setText("");
        this.j4.setText("");
        this.j5.setText("");
        this.j6.setText("");
        this.j7.setText("");
        this.j8.setText("");
        this.j9.setText("");
    
        
        
        this.jWin.setText("");
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel jTitle;
    private javax.swing.JLabel jWin;
    private javax.swing.JLabel jX;
    // End of variables declaration//GEN-END:variables
}
